[2023-01-20 13:25:31,355][__main__][CRITICAL] - Prediction failed due to [Errno 2] No such file or directory: '.\\big-lama\\config.yaml':
Traceback (most recent call last):
  File "./bin/predict.py", line 48, in main
    with open(train_config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\big-lama\\config.yaml'

